// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Guia da Riqueza - Transforme sua Mentalidade Financeira",
  description: "Plataforma completa para desenvolver mentalidade de riqueza com IA, ferramentas financeiras, áudios motivacionais e desafios diários. Conquiste sua prosperidade financeira!",
  keywords: "riqueza, mentalidade financeira, investimentos, prosperidade, dinheiro, sucesso financeiro, educação financeira",
  authors: [{ name: "Guia da Riqueza" }],
  openGraph: {
    title: "Guia da Riqueza - Transforme sua Mentalidade Financeira",
    description: "Plataforma completa para desenvolver mentalidade de riqueza com IA, ferramentas financeiras e conteúdo exclusivo",
    type: "website",
    locale: "pt_BR",
  },
  twitter: {
    card: "summary_large_image",
    title: "Guia da Riqueza - Transforme sua Mentalidade Financeira",
    description: "Plataforma completa para desenvolver mentalidade de riqueza com IA, ferramentas financeiras e conteúdo exclusivo",
  },
  robots: {
    index: true,
    follow: true,
  },
  viewport: "width=device-width, initial-scale=1",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
        <link rel="icon" href="/icon.svg" type="image/svg+xml" />
        <link rel="apple-touch-icon" href="/icon.svg" />
        <meta name="theme-color" content="#EAB308" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}